- name: Install redis server
  apt:
    name: redis-server
    state: present
    update_cache: yes

- name: Update Redis Config from Locai address to 0.0.0.0
  replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Redis
  systemd:
    name: redis
    state: restarted
    enabled: yes