- name: Demo on vars
  hosts: all
  vars:
    URL: play.example.com
    PROJECT: example
  vars_files:
    - example-vars.yml
  tasks:
    - name: Print URL
      debug:
        msg: URL = {{ URL }}
    - name: Print URL from Task
      debug:
        msg: URL = {{ URL }}
      vars:
        URL: task.example.com