- name: Demo on loops
  hosts: all
  tasks:
    - name: Print colours name
      debug:
        msg: "colours = {{ item }}"
      loop:
        - sky blue
        - baby pink
        - orange
        - black