- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
- name: Delete the default content
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
    - /var/www/html/index.nginx-debian.html
- name: Clean the old artifacts
  file:
    path: /var/www/html/{{COMPONENT}}
    state: absent
- name: Create the artifact path
  file:
    path: /var/www/html/{{COMPONENT}}
    state: directory
- name: Download artifact from nexus
  get_url:
    url: http://172.31.1.61:8081/repository/frontend/frontend-{{APP_VERSION}}.zip
    dest: /tmp/frontend.zip
    username: admin
    password: admin123

- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: /tmp/frontend.zip
    dest: /var/www/html/frontend
    remote_src: yes
- name: Insert the conf file
  template:
    src: todo.conf
    dest: /var/www/html/config/todo.conf
  notify: Restart Nginx
  
- name: Start Nginx
  systemd:
    state: started
    name: nginx
    enabled: yes