- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
- name: Delete the default content
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
    - /var/www/html/index.nginx-debian.html
- name: Clean the old artifacts
  file:
    path: /var/www/html/{{COMPONENT}}
    state: absent
- name: Create the artifact path
  file:
    path: /var/www/html/{{COMPONENT}}
    state: directory
- name: Download artifact from nexus
      get_url:
        url: http://172.31.1.61:8081/repository/frontend/frontend-{{APP_VERSION}}.zip
        dest: /tmp/frontend.zip
        username: admin
        password: admin123
- name: Insert the conf file
  template:
    src: todo.conf
    dest: /etc/nginx/sites-enabled/todo.conf
  notify: Restart Nginx
- name: Start Nginx
  systemd:
    state: started
    name: nginx
    enabled: yes