- name: Install nginx
  apt:
    name: nginx
    update_cache: yes
    state: present

- name: Download frontend from nexus
  get_url:
    url: http://:8081/repository/frontend/frontend-{{APP_VERSION}}.zip
    dest: /tmp/frontend.zip
    username: admin
    password: admin123

- name: Delete the default content
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
    - /var/www/html

- name: Create HtDocs directory
  file:
    path: /var/www/html
    state: directory

- name: Unzip download content
  unarchive:
    src: /tmp/frontend.zip
    dest: /var/www/html
    remote_src: yes

- name: start nginx
  systemd:
    state: started
    name: nginx
    enabled: yes
