- name: Install java
  become: yes
  apt:
    name: openjdk-8-jdk
    state: present
    update_cache: yes

- name: Install mvn
  become: yes
  apt:
    name: maven
    state: present

- name: Download artifacts from nexus
  include_tasks: download-nexus-artifacts.yml

- name: setup systemd service 
  include_tasks: setup-systemd.yml
