- name: Copy {{COMPONENT}} Service file
  template: 
    src: "{{COMPONENT}}.service"
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: start {{COMPONENT}} service
  systemd:
    name: "{{COMPONENT}}"
    daemon_reload: yes
    state: started
    enabled: yes
